services:
  cargo-transportation-tomcat:
    container_name: cargo_transportation_tomcat
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "28080:8080"
    depends_on:
      - db
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data_message
