spring:
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/test_db
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security-setting:
  sign-up-urls: "/api/auth/**, /swagger-ui/**, /api-docs/**"
  token-prefix: Bearer
  header-string: Authorization
  content-type: application/json
  access-expiration-time: 600000
  refresh-expiration-time: 3600000
  allowed-clock-skew-seconds: 180
